<?php echo $this->doctype() ?>
<html>
<head>
  <meta charset="UTF-8">
  <title>Zend Framework Quickstart Application</title>
  <base href="<?php echo URL_BASE; ?>">
  <?php echo $this->headLink()->appendStylesheet('css/global.css') ?>
</head>
<body>
<div id="header">
    <div id="header-logo" style="float: left">
        <strong>ZF Quickstart Application</strong>
    </div>
    <div id="header-navigation" style="float: right">
        <!-- <a href="<?php echo $this->url(
            array('controller'=>'guestbook'),
            'default',
            true) ?>">Guestbook</a> -->
    </div>
</div>

    <hr>
<?php echo $this->layout()->content ?>
    <hr>
    
    <div>Rodape</div>

</body>
</html>
