-- MySQL Script generated by MySQL Workbench
-- Sat 31 May 2014 10:54:07 AM BRT
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema vendas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cliente` (
  `idcliente` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `ativo` CHAR(1) NOT NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(45) NOT NULL,
  `status` CHAR(1) NOT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produto` (
  `idproduto` INT(11) NOT NULL AUTO_INCREMENT,
  `produto` VARCHAR(100) NOT NULL,
  `preco` DECIMAL(8,2) NOT NULL,
  `status` CHAR(1) NOT NULL,
  `idcategoria` INT NOT NULL,
  `saldo` INT NOT NULL,
  PRIMARY KEY (`idproduto`),
  INDEX `fk_produto_categoria_idx` (`idcategoria` ASC),
  CONSTRAINT `fk_produto_categoria`
    FOREIGN KEY (`idcategoria`)
    REFERENCES `categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venda` (
  `idvenda` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME NULL,
  `idcliente` INT(11) NOT NULL,
  `status` CHAR(1) NULL,
  PRIMARY KEY (`idvenda`),
  INDEX `fk_venda_cliente1_idx` (`idcliente` ASC),
  CONSTRAINT `fk_venda_cliente1`
    FOREIGN KEY (`idcliente`)
    REFERENCES `cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vendaitem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendaitem` (
  `idproduto` INT(11) NOT NULL,
  `idvenda` INT NOT NULL,
  `preco` DECIMAL(8,2) NOT NULL,
  `precopago` DECIMAL(8,2) NOT NULL,
  `qtd` INT NULL,
  PRIMARY KEY (`idproduto`, `idvenda`),
  INDEX `fk_produto_has_venda_venda1_idx` (`idvenda` ASC),
  INDEX `fk_produto_has_venda_produto1_idx` (`idproduto` ASC),
  CONSTRAINT `fk_produto_has_venda_produto1`
    FOREIGN KEY (`idproduto`)
    REFERENCES `produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_has_venda_venda1`
    FOREIGN KEY (`idvenda`)
    REFERENCES `venda` (`idvenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` CHAR(32) NOT NULL,
  `status` CHAR(1) NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data
-- -----------------------------------------------------

START TRANSACTION;
INSERT INTO `usuario` (`idusuario`, `nome`, `email`, `senha`, `status`) VALUES (NULL, 'Admin', 'admin@admin.com', '21232f297a57a5a743894a0e4a801fc3', '1');

INSERT INTO `cliente` (`idcliente`, `nome`, `email`, `ativo`) VALUES (NULL, 'Homer Simpsom', 'homer@gmail.com', '1');
INSERT INTO `cliente` (`idcliente`, `nome`, `email`, `ativo`) VALUES (NULL, 'Super Homem', 'super@homem.com', '1');
INSERT INTO `cliente` (`idcliente`, `nome`, `email`, `ativo`) VALUES (NULL, 'Mulher Maravilha', 'mm@gmail.com', '1');

INSERT INTO `categoria` (`idcategoria`, `categoria`, `status`) VALUES (NULL, 'Computadores', '1');
INSERT INTO `categoria` (`idcategoria`, `categoria`, `status`) VALUES (NULL, 'Monitores', '1');
INSERT INTO `categoria` (`idcategoria`, `categoria`, `status`) VALUES (NULL, 'Acessórios', '1');

INSERT INTO `produto` (`idproduto`, `produto`, `preco`, `status`, `idcategoria`, `saldo`) VALUES (NULL, 'Notebook', 2000, '1', 1, 10);
INSERT INTO `produto` (`idproduto`, `produto`, `preco`, `status`, `idcategoria`, `saldo`) VALUES (NULL, 'Teclado', 25, '1', 1, 20);
INSERT INTO `produto` (`idproduto`, `produto`, `preco`, `status`, `idcategoria`, `saldo`) VALUES (NULL, 'Monitor 22', 400, '1', 2, 15);
INSERT INTO `produto` (`idproduto`, `produto`, `preco`, `status`, `idcategoria`, `saldo`) VALUES (NULL, 'Caixa de Som', 50.5, '1', 3, 20);
INSERT INTO `produto` (`idproduto`, `produto`, `preco`, `status`, `idcategoria`, `saldo`) VALUES (NULL, 'Monitor 19', 300, '1', 2, 5);

COMMIT;

